=== council-of-rivendell/MeCCG-Windows-EN/core/xml/gccg-set.dtd
<!ENTITY % mtg-attr "color|type|subtype|rarity|cost|power|toughness">
<!ENTITY % metw-attr "region|move_to|site_path|haven|haven1|haven2|draw|site_type|auto_attack|playable|special|class|mp|corruption|prowess|body|influence|mind|home_site|race|skills|subclass|strikes|region_type|draw_opp|magic|spawn|sp|specific|gi|adjacent|agent">
<!ENTITY % pokemon-attr "evolve|retreat|weakness|hp|attack1|attack2|resistance">
<!ENTITY % lotr-attr "block|card_number|class|culture|expansion|home|race|rarity|signet|site|strength|twilight_cost|type|unique|vitality">

<!ELEMENT ccg-setinfo (cards)>
<!ATTLIST ccg-setinfo
    name        CDATA #REQUIRED
    dir         CDATA #IMPLIED
    abbrev      CDATA #IMPLIED
    game        CDATA #REQUIRED>
<!ELEMENT cards (card+)>
<!ATTLIST card
    name        CDATA #REQUIRED
    graphics    CDATA #REQUIRED
    back        CDATA #IMPLIED
    text        CDATA #IMPLIED>
<!ELEMENT card (attr*)>
<!ELEMENT attr EMPTY>
<!ATTLIST attr
    key         (%mtg-attr;|%metw-attr;|%pokemon-attr;|%lotr-attr;) #REQUIRED
    value       CDATA #REQUIRED>

=== council-of-rivendell/MeCCG-Windows-EN/core/xml/Metw/promo.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ccg-setinfo SYSTEM "../gccg-set.dtd">
<ccg-setinfo name="Promotional" dir="Promo" abbrev="PR" game="Middle-earth">
  <cards>

    <card name="Fury of the Iron Crown" graphics="FuryoftheIronCrown.jpg" text="Unique. May not be played if The Iron Crown is in play. The prowess of one strike of an attack by an Orc, Troll, Man, or Nazgul creature is increased by +4. After the attack is resolved, if the creature is not a Nazgul: the creature is removed from play (defender receives the marshalling points); and, in addition, if the defender has The Iron Crown in his hand, he may immediately play it with a character in the defending company.">
       <attr key="unique" value="yes"/>
       <attr key="rarity" value="P"/>
       <attr key="class" value="Short-event"/>
       <attr key="type" value="Hazard"/>
    </card>
    <card name="Angmar Arises" graphics="AngmarArises.jpg" text="Any creature that can be keyed to a Shadow-land {s} may be keyed to Forochel, Arthedain, Gundabad, or Rhudaur. Any creature that can be keyed to a Dark-domain {d} may be keyed to Angmar or Gundabad. Discard this card when a creature keyed to one of these regions (not to the region symbol) is defeated. {green} DCE: Replace with: Any creature that can be keyed to a Shadow-land may be keyed to Arthedain, Angmar, Dragon Gap, Everdalf, Forochel, Gundabad, or Rhudaur. Any creature that can be keyed to a Dark-domain may be keyed to Angmar. Dragon Gap, or Gundabad. Discard this card when a creature keyed to one of these regions (not to the region symbol) is defeated.">
       <attr key="rarity" value="P"/>
       <attr key="class" value="Permanent-event"/>
       <attr key="type" value="Hazard"/>
    </card>
    <card name="Never Seen Him" graphics="NeverSeenHim.jpg" text="Playable on an agent. Target agent may take an extra agent action (which does not count against the hazard limit) each time he normally takes an agent action. Cannot be duplicated on a given agent.">
       <attr key="rarity" value="P"/>
       <attr key="class" value="Permanent-event"/>
       <attr key="type" value="Hazard"/>
    </card>
    <card name="Neeker-breekers" graphics="Neekerbreekers.jpg" text="Animals. Does not effect Wizards. Each character in the company faces one strike. His prowess against such a strike is equal to his mind attribute. Any character that would normally be wounded is only tapped intstead - no body checks are made.">
       <attr key="strikes" value="1/each"/>
       <attr key="mp" value="1"/>
       <attr key="body" value="-"/>
       <attr key="playable" value="{b}{w}{s}{d}{R}"/>
       <attr key="prowess" value="7"/>
       <attr key="rarity" value="P"/>
       <attr key="subclass" value="Animals"/>
       <attr key="type" value="Hazard"/>
       <attr key="class" value="Creature"/>
	   <attr key="keyword" value="Vermin"/>
    </card>
    <card name="Black Arrow" graphics="BlackArrow.jpg" text="Warrior only. Tap Black Arrow to give -1 to the prowess and body of any one attack against bearer's company. When Black Arrow is tapped, discard it if its bearer is not a Man.">
       <attr key="corruption" value="1"/>
       <attr key="rarity" value="P"/>
       <attr key="class" value="Minor Item"/>
       <attr key="type" value="Hero Resource"/>
	   <attr key="keyword" value="Battle-gear"/>
    </card>
    <card name="More Alert than Most" graphics="MoreAlertthanMost.jpg" text="The number of strikes of any attack that chooses defending characters is reduced by one (to a minimum of one) - by two if Gates of Morning is in play. Discard when such attack is defeated. Cannot be duplicated.">
       <attr key="rarity" value="P"/>
       <attr key="class" value="Permanent-event"/>
       <attr key="type" value="Hero Resource"/>
    </card>
    <card name="Ireful Flames" graphics="IrefulFlames.jpg" text="Affects the following sites: The Loney Mountain, Irerock, Zarak Dum, and Gold Hill. For any item to be played at one of these sites, its player must remove an item in his hand from play that would itself be playable at the site. Cannot be revealed as an on-guard card. Discard Ireful Flames when any play deck is exhausted. {green} DCE: Add: Affects the following sites: Cirith Helkaloke, Norr-dûm, Shab Arch and Turukulon's Lair.">
       <attr key="rarity" value="P"/>
       <attr key="class" value="Permanent-event"/>
       <attr key="type" value="Hazard"/>
    </card>
    <card name="Stormcrow" graphics="Stormcrow.jpg" text="The direct influence of each Wizard is reduced by 2 (by 4 if Doors of Night is in play). Discard all resource permanent-events that have been played on each company with a Wizard (i.e., on the company as a whole, not individual characters, e.g., Fellowship). No such cards may be played on each Wizard's company. Discard this card when any play deck is exhausted. Cannot be duplicated.">
       <attr key="rarity" value="P"/>
       <attr key="class" value="Permanent-event"/>
       <attr key="type" value="Hazard"/>
    </card>
    <card name="Fatty Bolger" graphics="FattyBolger.jpg" text="Unique. Unless he is one of the starting characters, he may only be brought into play at his home site. All his corruption checks are modified by +1. He can tap to cancel a strike against another hobbit in his company.">
       <attr key="unique" value="yes"/>
       <attr key="corruption" value="+1"/>
       <attr key="skills" value="Scout"/>
       <attr key="mp" value="1"/>
       <attr key="body" value="8"/>
       <attr key="prowess" value="1"/>
       <attr key="home_site" value="Bag End"/>
       <attr key="rarity" value="P"/>
       <attr key="race" value="Hobbit"/>
       <attr key="type" value="Hero Character"/>
       <attr key="mind" value="3"/>
       <attr key="influence" value="0"/>
    </card>
    <card name="Bill Ferny" graphics="BillFerny.jpg" text="Unique.">
       <attr key="unique" value="yes"/>
       <attr key="skills" value="Warrior/Scout"/>
       <attr key="mp" value="1"/>
       <attr key="body" value="8"/>
       <attr key="prowess" value="2"/>
       <attr key="home_site" value="Bree, Cameth Brin"/>
       <attr key="rarity" value="P"/>
       <attr key="race" value="Man"/>
       <attr key="agent" value="yes"/>
       <attr key="type" value="Minion Character"/>
       <attr key="mind" value="3"/>
       <attr key="influence" value="1"/>
    </card>
    <card name="The Arkenstone" graphics="TheArkenstone.jpg" text="Unique. +5 to bearer's direct influence against Dwarves and Dwarf factions. Each Dwarf in play has +1 mind. If the bearer of this item is at the same site as a Dwarf character, you may discard this item to force the discard of the Dwarf (and all non-follower cards he controls).">
       <attr key="unique" value="yes"/>
       <attr key="corruption" value="3"/>
       <attr key="mp" value="3"/>
       <attr key="rarity" value="P"/>
       <attr key="class" value="Greater Item"/>
       <attr key="type" value="Minion Resource"/>
       <attr key="influence" value="(+5)"/>
	   <attr key="keyword" value="Jewel"/>
	   <attr key="keyword" value="Hoard Item"/>
    </card>
    <card name="Deadly Dart" graphics="DeadlyDart.jpg" text="Scout only. Tap Deadly Dart to give -1 body and -1 strike (to a minimum of one) to an automatic-attack or to a hazard creature keyed to a site. Tap its bearer or discard Deadly Dart when it is tapped. May also be used as a hero resource (i.e., included in a Wizard's deck), but may not be included with a hero starting company.">
       <attr key="corruption" value="2"/>
       <attr key="rarity" value="P"/>
       <attr key="class" value="Minor Item"/>
       <attr key="type" value="Minion Resource"/>
	   <attr key="keyword" value="Battle-gear"/>
    </card>
    <card name="The Iron Crown" graphics="TheIronCrown.jpg" text="Unique. Whenever bearer makes an influence check, he must also make a corruption check. If the bearer is not a Hobbit: he receives +1 to body to a maximum of 10; he receives +4 to direct influence; and he may tap The Iron Crown to cancel an attack by Orcs, Trolls, or Men against his company.">
       <attr key="unique" value="yes"/>
       <attr key="corruption" value="5"/>
       <attr key="mp" value="4"/>
       <attr key="body" value="(+1)"/>
       <attr key="rarity" value="P"/>
       <attr key="class" value="Greater Item"/>
       <attr key="type" value="Hero Resource"/>
       <attr key="influence" value="(+4)"/>
	   <attr key="keyword" value="Battle-gear"/>
	   <attr key="keyword" value="Helmet"/>
    </card>
  </cards>
</ccg-setinfo>

=== council-of-rivendell/MeCCG-Windows-EN/core/sample/xml/Sample/basecards.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ccg-setinfo SYSTEM "../gccg-set.dtd">
<ccg-setinfo name="" game="Name of the Game">

  <cards>
    <card name="A Card" text="" graphics="cardback.jpg">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
  </cards>

</ccg-setinfo>

=== council-of-rivendell/MeCCG-Windows-EN/core/xml/Metw/firstborn_promo.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ccg-setinfo SYSTEM "../gccg-set.dtd">
<ccg-setinfo name="Firstborn Promo" dir="firstborn_promo" abbrev="FP" game="Middle-earth">
	<cards>
		<card name="Camthalion" graphics="Camthalion.jpg" text="Unique. Elf. 1 strike. +2 prowess against Elves.May be played keyed to any Dark-domain [d] or Dark-hold [D], if there is a Nazgul permanent-event or Ringwraith in play, or to any Shadow-hold [S] following a Nazgul attack. Cannot be targetted by spells or magic. As a short-event, playable on a hero character moving through a Dark-domain or to/from a Dark-hold. Character loses all his skills for the rest of the turn; discard any Knowledge or Information events he controls.">
			 <attr key="type" value="Hazard"/>
			 <attr key="rarity" value="P"/>
			 <attr key="unique" value="yes"/>
			 <attr key="class" value="Creature/Short-event"/>
			 <attr key="prowess" value="12/8"/>
			 <attr key="mp" value="2"/>
			 <attr key="strikes" value="1"/>
			 <attr key="subclass" value="Elves"/>
		</card>
		<card name="Ellindiel" graphics="Ellindiel.jpg" text="Unique. Noldo. Grey Agent. +2 EI against characters with a home site in Eriador. Discard if in company with an Elf or Dúnadan with a higher mind.Any Wisp of Pale Sheen may be played keyed to Ellindiel's current non-Free-hold [F] site.">
			 <attr key="type" value="Grey Agent Character"/>
			 <attr key="rarity" value="P"/>
			 <attr key="unique" value="yes"/>
			 <attr key="prowess" value="3/8"/>
			 <attr key="mind" value="7"/>
			 <attr key="influence" value="2"/>
			 <attr key="mp" value="2"/>
			 <attr key="home_site" value="Any site in Arthedain"/>
			 <attr key="agent" value="yes"/>
			 <attr key="subclass" value="Grey Agent"/>
			 <attr key="race" value="Elf"/>
			 <attr key="keyword" value="Grey Agent"/>
			 <attr key="keyword" value="Noldo"/>
		</card>
		<card name="Elves of Edhellond" graphics="Elves of Edhellond.jpg" text="Unique. Playable at Edhellond if the influence check is greater than 10.Standard Modifications: Elves (+2), Dúnedain (+1), character with home site Edhellond (+2). This faction is worth 2 mp if no manifestation of Eärcaraxë is in active play. If Círdor is at Edhellond, you may play Sail to the West as if at Grey Havens.">
			 <attr key="type" value="Hero Resource"/>
			 <attr key="rarity" value="P"/>
			 <attr key="unique" value="yes"/>
			 <attr key="class" value="Elf Faction"/>
			 <attr key="mp" value="1(2)"/>
		</card>
		<card name="Kheleglin" graphics="Kheleglin.jpg" text="Unique. Elf. Noldo. Playable at any Dark-hold [D], if you discard (for no effect) a Stolen Knowledge card from the company. Kheleglin comes into play wounded. tap: if at an Elf-hold and discard a (stored) Reforging from his company to search your discard pile or sideboard.for a Noldo Lantern, which may be placed with a character in the company.">
			 <attr key="type" value="Stage Resource"/>
			 <attr key="rarity" value="P"/>
			 <attr key="unique" value="yes"/>
			 <attr key="class" value="Sage Ally"/>
			 <attr key="prowess" value="3/9"/>
			 <attr key="mind" value="3"/>
			 <attr key="mp" value="2"/>
			 <attr key="keyword" value="Noldo"/>
		</card>
		<card name="Maranya" graphics="Maranya.jpg" text="Unique. Mind Ring. Playable on Celedhring at Barad-dûr(or in your starting company in lieu of a minor item). You may play Mithril and Vein of Arda as minion resources. Celedhring only: during site phase at a Shadow-hold [S] or Dark-hold [D] you may:tap: store and/or play Dark Forges as if at a Darkhaven [K].tap: place a Vein of Arda or Mithril in the company with an item in the company: it becomes a jewel and all of its bonusses are increased by 1.Celedhring makes a corruption check at -2.">
			 <attr key="type" value="Minion Resource"/>
			 <attr key="rarity" value="P"/>
			 <attr key="unique" value="yes"/>
			 <attr key="class" value="Special Item"/>
			 <attr key="mind" value="-1"/>
			 <attr key="influence" value="+1"/>
			 <attr key="cp" value="2"/>
			 <attr key="keyword" value="Mind Ring"/>
		</card>
	</cards>
</ccg-setinfo>

=== council-of-rivendell/MeCCG-Windows-EN/core/xml/Metw/metw_basecards.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE ccg-setinfo SYSTEM "../gccg-set.dtd">
<ccg-setinfo name="" game="Middle-earth">

  <cards>
    <card name="A Card" text="" graphics="metw-back.jpg">
    </card>
    <card name="A Site" text="" back="1" graphics="site-back.jpg">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
    <card name="_unknown_" text="" graphics="">
    </card>
  </cards>

</ccg-setinfo>
